all:
	cd CircuitRouter-ParSolver && make
	cd CircuitRouter-SeqSolver && make
clean:
	cd CircuitRouter-ParSolver && make clean
	cd CircuitRouter-SeqSolver && make clean
	rm -rf inputs/*.old
	rm -rf inputs/*.res
