all:
	cd lib && make
	cd CircuitRouter-SeqSolver && make
	cd CircuitRouter-SimpleShell && make
clean:
	cd CircuitRouter-SeqSolver && make clean
	cd CircuitRouter-SimpleShell && make clean
	cd lib && make clean
